import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import YAML from "../../scripts/lib/yaml-loader.mjs";

const openapiPath = resolve("contracts/openapi/api.yaml");
const clientOutputDir = resolve("tests/web-harness/src/api-gen");
const apiOutputDir = resolve(clientOutputDir, "api");
const coreOutputDir = resolve(clientOutputDir, "core");
const mswOutputDir = resolve("tests/web-harness/msw");

const requestOutputFile = resolve(coreOutputDir, "request.ts");
const healthOutputFile = resolve(apiOutputDir, "health.ts");
const automationOutputFile = resolve(apiOutputDir, "automation.ts");
const commandTowerOutputFile = resolve(apiOutputDir, "command-tower.ts");
const clientOutputFile = resolve(clientOutputDir, "client.ts");
const mswOutputFile = resolve(mswOutputDir, "handlers.ts");
const verifyMode = process.argv.includes("--verify");

type OpenApiSpec = {
  paths?: Record<
    string,
    Record<string, { operationId?: string; responses?: Record<string, unknown> }>
  >;
};

type Operation = {
  path: string;
  method: string;
  operationId: string;
};

type PathParam = {
  raw: string;
  name: string;
};

type ApiModuleName = "health" | "automation" | "command-tower";

function toPascalCase(value: string): string {
  return value
    .replace(/[{}]/g, "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join("");
}

function buildOperationId(method: string, path: string): string {
  return `${method.toLowerCase()}${toPascalCase(path)}`.replace(/[^a-zA-Z0-9_]/g, "");
}

function extractOperations(spec: OpenApiSpec): Operation[] {
  const ops: Operation[] = [];
  const supportedMethods = new Set(["get", "post", "put", "patch", "delete"]);
  for (const [path, methods] of Object.entries(spec.paths ?? {})) {
    for (const [method, operation] of Object.entries(methods ?? {})) {
      if (!supportedMethods.has(method.toLowerCase())) continue;
      const operationId = operation?.operationId?.trim() || buildOperationId(method, path);
      ops.push({ path, method: method.toUpperCase(), operationId });
    }
  }
  return ops;
}

function extractPathParams(path: string): PathParam[] {
  const matches = path.matchAll(/\{([^}]+)\}/g);
  return Array.from(matches, (match) => {
    const raw = match[1];
    return {
      raw,
      name: raw.replace(/[^a-zA-Z0-9_$]/g, "_"),
    };
  });
}

function buildResolvedPath(path: string, pathParams: PathParam[]): string {
  return pathParams.reduce((resolved, param) => {
    return resolved.replaceAll(
      `{${param.raw}}`,
      `\${encodeURIComponent(pathParams.${param.name})}`,
    );
  }, path);
}

function resolveApiModule(path: string): ApiModuleName {
  if (path === "/" || path === "/metrics" || path.startsWith("/health/")) {
    return "health";
  }
  if (path.startsWith("/api/command-tower/")) {
    return "command-tower";
  }
  return "automation";
}

function groupOperationsByModule(operations: Operation[]): Record<ApiModuleName, Operation[]> {
  const grouped: Record<ApiModuleName, Operation[]> = {
    health: [],
    automation: [],
    "command-tower": [],
  };
  for (const operation of operations) {
    grouped[resolveApiModule(operation.path)].push(operation);
  }
  return grouped;
}

function buildRequestCore(): string {
  return `// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

export const DEFAULT_REQUEST_TIMEOUT_MS = 30_000;

let defaultRequestTimeoutMs = DEFAULT_REQUEST_TIMEOUT_MS;

export type RequestJsonInit = RequestInit & {
  timeoutMs?: number;
};

type StructuredErrorBody = {
  detail?: unknown;
  message?: unknown;
  error?: unknown;
  rawText?: string;
};

export class ApiRequestError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly method: string;
  readonly url: string;
  readonly body: StructuredErrorBody;

  constructor(
    message: string,
    details: {
      status: number;
      statusText: string;
      method: string;
      url: string;
      body: StructuredErrorBody;
    },
  ) {
    super(message);
    this.name = "ApiRequestError";
    this.status = details.status;
    this.statusText = details.statusText;
    this.method = details.method;
    this.url = details.url;
    this.body = details.body;
  }
}

export function setDefaultRequestTimeoutMs(timeoutMs: number): void {
  if (!Number.isFinite(timeoutMs) || timeoutMs < 0) {
    throw new Error("default request timeout must be a non-negative finite number");
  }
  defaultRequestTimeoutMs = timeoutMs;
}

function isJsonContentType(contentType: string): boolean {
  return contentType.includes("application/json") || contentType.includes("+json");
}

function tryParseJson(value: string): unknown | undefined {
  try {
    return JSON.parse(value);
  } catch {
    return undefined;
  }
}

function toDiagnosticText(value: unknown): string | undefined {
  if (typeof value === "string" && value.trim().length > 0) {
    return value;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value && typeof value === "object") {
    const messageValue = (value as Record<string, unknown>).message;
    if (typeof messageValue === "string" && messageValue.trim().length > 0) {
      return messageValue;
    }
  }
  return undefined;
}

function buildErrorBody(text: string): StructuredErrorBody {
  const structured: StructuredErrorBody = {};
  if (text.length === 0) {
    return structured;
  }
  const parsed = tryParseJson(text);
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    const parsedObject = parsed as Record<string, unknown>;
    if ("detail" in parsedObject) structured.detail = parsedObject.detail;
    if ("message" in parsedObject) structured.message = parsedObject.message;
    if ("error" in parsedObject) structured.error = parsedObject.error;
  }
  structured.rawText = text;
  return structured;
}

function buildErrorMessage(status: number, statusText: string, body: StructuredErrorBody): string {
  const diagnostic = [
    toDiagnosticText(body.detail),
    toDiagnosticText(body.message),
    toDiagnosticText(body.error),
    body.rawText?.trim() || undefined,
  ].find((value) => value && value.length > 0);
  if (!diagnostic) {
    return \`API request failed: \${status} \${statusText}\`;
  }
  return \`API request failed: \${status} \${statusText} - \${diagnostic}\`;
}

function mergeAbortSignal(timeoutMs: number, externalSignal?: AbortSignal): {
  signal: AbortSignal | undefined;
  cleanup: () => void;
} {
  if (!externalSignal && timeoutMs <= 0) {
    return { signal: undefined, cleanup: () => {} };
  }
  if (externalSignal && timeoutMs <= 0) {
    return { signal: externalSignal, cleanup: () => {} };
  }

  const controller = new AbortController();
  const abortFromExternal = () => {
    controller.abort(externalSignal?.reason);
  };
  if (externalSignal?.aborted) {
    abortFromExternal();
  } else if (externalSignal) {
    externalSignal.addEventListener("abort", abortFromExternal, { once: true });
  }

  const timeoutHandle = setTimeout(() => {
    controller.abort(new Error(\`Request timed out after \${timeoutMs}ms\`));
  }, timeoutMs);

  return {
    signal: controller.signal,
    cleanup: () => {
      clearTimeout(timeoutHandle);
      if (externalSignal) {
        externalSignal.removeEventListener("abort", abortFromExternal);
      }
    },
  };
}

export async function requestJson(
  baseUrl: string,
  path: string,
  method: string,
  init?: RequestJsonInit,
): Promise<unknown> {
  const { timeoutMs, signal: externalSignal, ...fetchInit } = init ?? {};
  const timeoutWithDefault = timeoutMs ?? defaultRequestTimeoutMs;

  const headers = new Headers(fetchInit.headers ?? {});
  if (!headers.has("content-type") && init?.body) {
    headers.set("content-type", "application/json");
  }
  const { signal, cleanup } = mergeAbortSignal(timeoutWithDefault, externalSignal);

  try {
    const response = await fetch(\`\${baseUrl}\${path}\`, {
      ...fetchInit,
      method,
      headers,
      signal,
    });
    const text = await response.text();
    if (!response.ok) {
      const body = buildErrorBody(text);
      throw new ApiRequestError(buildErrorMessage(response.status, response.statusText, body), {
        status: response.status,
        statusText: response.statusText,
        method,
        url: \`\${baseUrl}\${path}\`,
        body,
      });
    }
    if (text.length === 0) {
      return undefined;
    }
    const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";
    if (!isJsonContentType(contentType)) {
      return text;
    }
    try {
      return JSON.parse(text);
    } catch {
      throw new Error("API response is not valid JSON");
    }
  } finally {
    cleanup();
  }
}
`;
}

function buildApiModule(operations: Operation[], operationsConstName: string): string {
  const methods = operations.map((op) => {
    const pathParams = extractPathParams(op.path);
    const pathParamsType =
      pathParams.length > 0
        ? `{ ${pathParams.map((param) => `${param.name}: string`).join("; ")} }`
        : null;
    const resolvedPath = buildResolvedPath(op.path, pathParams);
    const args = ["baseUrl: string"];
    if (pathParamsType) {
      args.push(`pathParams: ${pathParamsType}`);
    }
    args.push("init?: RequestInit");

    const argLines = args.map((arg) => `  ${arg},`);
    return [
      `export async function ${op.operationId}(`,
      ...argLines,
      "): Promise<unknown> {",
      "  return requestJson(",
      "    baseUrl,",
      `    \`${resolvedPath}\`,`,
      `    "${op.method}",`,
      "    init,",
      "  );",
      "}",
    ].join("\n");
  });

  const operationsConst =
    operations.length > 0
      ? [
          `export const ${operationsConstName} = [`,
          ...operations.flatMap((op) => [
            "  {",
            `    operationId: "${op.operationId}",`,
            `    method: "${op.method}",`,
            `    path: "${op.path}",`,
            "  },",
          ]),
          "] as const;",
        ].join("\n")
      : `export const ${operationsConstName} = [] as const;`;

  const blocks = [
    "// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.",
    'import { requestJson } from "../core/request";',
    ...methods,
    operationsConst,
  ];
  return `${blocks.join("\n\n")}\n`;
}

function buildClientCompat(): string {
  return [
    "// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.",
    'import { AUTOMATION_API_OPERATIONS } from "./api/automation";',
    'import { COMMAND_TOWER_API_OPERATIONS } from "./api/command-tower";',
    'import { HEALTH_API_OPERATIONS } from "./api/health";',
    "",
    'export * from "./api/automation";',
    'export * from "./api/command-tower";',
    'export * from "./api/health";',
    "",
    "export const API_OPERATIONS = [",
    "  ...HEALTH_API_OPERATIONS,",
    "  ...AUTOMATION_API_OPERATIONS,",
    "  ...COMMAND_TOWER_API_OPERATIONS,",
    "] as const;",
    "",
  ].join("\n");
}

function buildMswHandlers(operations: Operation[]): string {
  const handlers = operations
    .map((op) => {
      const mswPath = op.path.replace(/\{([a-zA-Z0-9_]+)\}/g, ":$1");
      return [
        "  http." + op.method.toLowerCase() + `(\"${mswPath}\", async () => {`,
        "    return HttpResponse.json({",
        `      operationId: \"${op.operationId}\",`,
        "      mocked: true,",
        "    });",
        "  }),",
      ].join("\n");
    })
    .join("\n\n");

  return [
    "// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.",
    'import { HttpResponse, http } from "msw";',
    "",
    "export const handlers = [",
    handlers,
    "];",
    "",
  ].join("\n");
}

function readOptionalFile(path: string): string | null {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
}

function formatWithBiome(content: string, filePath: string): string {
  try {
    const formatted = execFileSync(
      "pnpm",
      ["exec", "biome", "format", "--stdin-file-path", filePath],
      {
        input: content,
        encoding: "utf8",
      },
    );
    return formatted;
  } catch {
    return content;
  }
}

const raw = readFileSync(openapiPath, "utf8");
const spec = YAML.parse(raw) as OpenApiSpec;
const operations = extractOperations(spec);
const groupedOperations = groupOperationsByModule(operations);

const generatedArtifacts = new Map<string, string>([
  [requestOutputFile, formatWithBiome(buildRequestCore(), requestOutputFile)],
  [
    healthOutputFile,
    formatWithBiome(
      buildApiModule(groupedOperations.health, "HEALTH_API_OPERATIONS"),
      healthOutputFile,
    ),
  ],
  [
    automationOutputFile,
    formatWithBiome(
      buildApiModule(groupedOperations.automation, "AUTOMATION_API_OPERATIONS"),
      automationOutputFile,
    ),
  ],
  [
    commandTowerOutputFile,
    formatWithBiome(
      buildApiModule(groupedOperations["command-tower"], "COMMAND_TOWER_API_OPERATIONS"),
      commandTowerOutputFile,
    ),
  ],
  [clientOutputFile, formatWithBiome(buildClientCompat(), clientOutputFile)],
  [mswOutputFile, formatWithBiome(buildMswHandlers(operations), mswOutputFile)],
]);

if (verifyMode) {
  const driftedFiles: string[] = [];
  for (const [file, content] of generatedArtifacts) {
    if (readOptionalFile(file) !== content) {
      driftedFiles.push(file);
    }
  }

  if (driftedFiles.length > 0) {
    console.error("Contract verify failed. Generated artifacts are out of date:");
    for (const file of driftedFiles) {
      console.error(`- ${file}`);
    }
    console.error("Run `pnpm contracts:generate` and commit the updated artifacts.");
    process.exit(1);
  }

  console.log("Contract verify passed. Generated artifacts are up to date.");
  process.exit(0);
}

mkdirSync(coreOutputDir, { recursive: true });
mkdirSync(apiOutputDir, { recursive: true });
mkdirSync(mswOutputDir, { recursive: true });

for (const [file, content] of generatedArtifacts) {
  writeFileSync(file, content, "utf8");
  console.log(`Generated ${file}`);
}
