export type ButtonBehaviorAssertionType =
  | "aria-current"
  | "aria-selected"
  | "visibility-toggle"
  | "text-visible"
  | "text-order-change"
  | "toast-visible"
  | "attribute-change"
  | "storage-change"
  | "list-count-change";

export type ButtonInventoryCoverageScope = "behavior-gated" | "inventory-only";
export type ButtonInteractionType =
  | "navigation"
  | "execution"
  | "danger-action"
  | "dialog"
  | "visibility-toggle"
  | "form-submit"
  | "state-toggle"
  | "list-action"
  | "utility";
export type RuntimeMode = "stub" | "non-stub" | "both";

export type ButtonBehaviorManifestEntry = {
  id: string;
  component_source: "frontend" | "tests/web-harness";
  view: string;
  selector: string;
  interaction_type: ButtonInteractionType;
  criticality: "critical" | "high" | "medium";
  expected_effect: string;
  coverage_scope: ButtonInventoryCoverageScope;
  spec_file: string;
  runtime_mode: RuntimeMode;
  is_apps_web: boolean;
  last_verified_command: string;
  assertion_type?: ButtonBehaviorAssertionType;
  case_id?: string;
};

export const BUTTON_BEHAVIOR_MANIFEST = [
  {
    id: "nav-tab-quick-launch",
    component_source: "frontend",
    view: "QuickLaunch",
    selector: "data-testid=console-tab-quick-launch",
    interaction_type: "navigation",
    criticality: "critical",
    expected_effect: "Switches to Quick Launch and activates the matching primary navigation tab.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.quick-launch.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "aria-selected",
    case_id: "nav-quick-launch-selected",
  },
  {
    id: "nav-tab-task-center",
    component_source: "frontend",
    view: "TaskCenter",
    selector: "data-testid=console-tab-task-center",
    interaction_type: "navigation",
    criticality: "critical",
    expected_effect: "Switches to Task Center and shows the task-center panel.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.task-center.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "aria-selected",
    case_id: "nav-task-center-selected",
  },
  {
    id: "nav-tab-flow-workshop",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=console-tab-flow-draft",
    interaction_type: "navigation",
    criticality: "high",
    expected_effect: "Switches to Flow Workshop and shows the workshop primary card.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "aria-selected",
    case_id: "nav-flow-workshop-selected",
  },
  {
    id: "taskcenter-tab-command-runs",
    component_source: "frontend",
    view: "TaskCenter",
    selector: "data-testid=task-center-tab-command-runs",
    interaction_type: "list-action",
    criticality: "high",
    expected_effect: "Shows the command-run records panel and hides the template-run panel.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.task-center.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "taskcenter-command-runs-visible",
  },
  {
    id: "taskcenter-tab-template-runs",
    component_source: "frontend",
    view: "TaskCenter",
    selector: "data-testid=task-center-tab-template-runs",
    interaction_type: "list-action",
    criticality: "high",
    expected_effect: "Shows the template-run records panel and hides the command-run panel.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.task-center.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "taskcenter-template-runs-visible",
  },
  {
    id: "quicklaunch-first-use-start-step",
    component_source: "frontend",
    view: "QuickLaunch",
    selector: 'role=button[name="Start step 1"]',
    interaction_type: "navigation",
    criticality: "high",
    expected_effect: "Moves the first-run guide from welcome to configure.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.quick-launch.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "quicklaunch-first-use-start-stage",
  },
  {
    id: "quicklaunch-enter-run-step",
    component_source: "frontend",
    view: "QuickLaunch",
    selector: 'role=button[name="Configuration complete, continue to run"]',
    interaction_type: "navigation",
    criticality: "high",
    expected_effect: "Moves the first-run guide into the run stage and shows the run instructions.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.quick-launch.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "quicklaunch-enter-run-stage",
  },
  {
    id: "quicklaunch-sidebar-toggle",
    component_source: "frontend",
    view: "QuickLaunch",
    selector: "aria-label=Collapse parameter panel",
    interaction_type: "visibility-toggle",
    criticality: "medium",
    expected_effect: "Toggles the parameter panel between collapsed and expanded states.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.quick-launch.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "quicklaunch-sidebar-toggle-panel",
  },
  {
    id: "commandgrid-category-pipeline",
    component_source: "frontend",
    view: "CommandGrid",
    selector: "data-testid=commandgrid-category-pipeline",
    interaction_type: "list-action",
    criticality: "high",
    expected_effect: "Filters the command-card list to the pipeline category.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.command-grid.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-pipeline",
  },
  {
    id: "commandgrid-run-command",
    component_source: "frontend",
    view: "CommandGrid",
    selector: 'role=button[name="Run"]',
    interaction_type: "execution",
    criticality: "critical",
    expected_effect: "Triggers the command execution API and shows the submitted-success feedback.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.command-grid.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "commandgrid-run-command-success",
  },
  {
    id: "flowworkshop-save-draft",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-save-draft",
    interaction_type: "execution",
    criticality: "high",
    expected_effect: "Saves the flow draft and shows the success feedback.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-save-draft-success",
  },
  {
    id: "flowworkshop-replay-latest",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: 'role=button[name="Replay latest flow"]',
    interaction_type: "execution",
    criticality: "critical",
    expected_effect: "Triggers replay for the latest flow and shows the success feedback.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-replay-latest-success",
  },
  {
    id: "helptour-open-panel",
    component_source: "frontend",
    view: "HelpTour",
    selector: "aria-label=Help",
    interaction_type: "dialog",
    criticality: "medium",
    expected_effect: "Opens the help panel and displays help content for the current view.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.help-tour.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "helptour-open-panel",
  },
  {
    id: "helptour-restart-onboarding",
    component_source: "frontend",
    view: "HelpTour",
    selector: "data-testid=helptour-restart-onboarding",
    interaction_type: "execution",
    criticality: "medium",
    expected_effect: "Resets onboarding state and reopens the onboarding overlay.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.help-tour.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "storage-change",
    case_id: "helptour-restart-onboarding",
  },
  {
    id: "params-toggle-register-password-visibility",
    component_source: "frontend",
    view: "Params",
    selector: "data-testid=params-toggle-register-password-visibility",
    interaction_type: "visibility-toggle",
    criticality: "medium",
    expected_effect: "Toggles the registration-password input between password and text.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.params.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "params-toggle-register-password-visibility",
  },
  {
    id: "params-toggle-token-visibility",
    component_source: "frontend",
    view: "Params",
    selector: "data-testid=params-toggle-token-visibility",
    interaction_type: "visibility-toggle",
    criticality: "medium",
    expected_effect: "Toggles the API token input between password and text.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.params.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "params-toggle-token-visibility",
  },
  {
    id: "console-restart-tour",
    component_source: "frontend",
    view: "ConsoleHeader",
    selector: "aria-label=Restart onboarding",
    interaction_type: "execution",
    criticality: "medium",
    expected_effect: "Restarts the first-run onboarding flow.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.quick-launch.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "storage-change",
    case_id: "console-restart-tour",
  },
  {
    id: "commandgrid-category-all",
    component_source: "frontend",
    view: "CommandGrid",
    selector: "data-testid=commandgrid-category-all",
    interaction_type: "list-action",
    criticality: "medium",
    expected_effect: "Switches to the complete command list.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.command-grid.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "commandgrid-filter-all",
  },
  {
    id: "commandgrid-category-pipeline-tab",
    component_source: "frontend",
    view: "CommandGrid",
    selector: "data-testid=commandgrid-category-pipeline",
    interaction_type: "list-action",
    criticality: "medium",
    expected_effect: "Switches to the pipeline category.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.command-grid.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "commandgrid-filter-pipeline-tab",
  },
  {
    id: "commandgrid-run-command-testid",
    component_source: "frontend",
    view: "CommandGrid",
    selector: "data-testid=commandgrid-run-command",
    interaction_type: "execution",
    criticality: "critical",
    expected_effect: "Triggers command execution through a stable selector.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.command-grid.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "commandgrid-run-command-testid",
  },
  {
    id: "tasklist-refresh",
    component_source: "frontend",
    view: "TaskCenter",
    selector: "data-testid=tasklist-refresh",
    interaction_type: "list-action",
    criticality: "high",
    expected_effect: "Refreshes the Task Center list.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.task-center.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "tasklist-refresh",
  },
  {
    id: "task-item-open",
    component_source: "frontend",
    view: "TaskCenter",
    selector: "data-testid=task-item-open",
    interaction_type: "list-action",
    criticality: "high",
    expected_effect: "Opens task details and highlights the current task.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.task-center.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "taskcenter-open-task-detail",
  },
  {
    id: "task-item-cancel",
    component_source: "frontend",
    view: "TaskCenter",
    selector: "data-testid=task-item-cancel",
    interaction_type: "danger-action",
    criticality: "high",
    expected_effect: "Cancels a running task.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.task-center.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "taskcenter-cancel-running-task",
  },
  {
    id: "confirm-dialog-overlay-close",
    component_source: "frontend",
    view: "ConfirmDialog",
    selector: "data-testid=confirm-dialog-overlay-close",
    interaction_type: "dialog",
    criticality: "medium",
    expected_effect: "Closes the confirmation dialog by clicking the overlay.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.confirm-dialog.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "confirm-dialog-overlay-close",
  },
  {
    id: "confirm-dialog-cancel",
    component_source: "frontend",
    view: "ConfirmDialog",
    selector: "data-testid=confirm-dialog-cancel",
    interaction_type: "dialog",
    criticality: "medium",
    expected_effect: "Cancels the dangerous confirmation without executing the action.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.confirm-dialog.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "confirm-dialog-cancel",
  },
  {
    id: "confirm-dialog-confirm",
    component_source: "frontend",
    view: "ConfirmDialog",
    selector: "data-testid=confirm-dialog-confirm",
    interaction_type: "danger-action",
    criticality: "critical",
    expected_effect: "Confirms the dangerous action and continues execution.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.confirm-dialog.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "confirm-dialog-confirm",
  },
  {
    id: "empty-state-action",
    component_source: "frontend",
    view: "SharedEmptyState",
    selector: "data-testid=empty-state-action",
    interaction_type: "utility",
    criticality: "medium",
    expected_effect: "Triggers the next step from an empty-state CTA.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.empty-state.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm --dir apps/command-center exec vitest run src/components/EmptyState.test.tsx",
    assertion_type: "aria-selected",
    case_id: "taskcenter-empty-state-action",
  },
  {
    id: "help-panel-overlay",
    component_source: "frontend",
    view: "HelpTour",
    selector: "data-testid=help-panel-overlay",
    interaction_type: "dialog",
    criticality: "medium",
    expected_effect: "Closes the help panel by clicking the overlay.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.help-tour.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "helptour-overlay-close",
  },
  {
    id: "help-panel-close",
    component_source: "frontend",
    view: "HelpTour",
    selector: "data-testid=help-panel-close",
    interaction_type: "dialog",
    criticality: "medium",
    expected_effect: "Closes the help panel through its close button.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.help-tour.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "visibility-toggle",
    case_id: "helptour-close-panel",
  },
  {
    id: "flowworkshop-add-step",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-add-step",
    interaction_type: "execution",
    criticality: "high",
    expected_effect: "Adds a new flow step.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "list-count-change",
    case_id: "flowworkshop-add-step",
  },
  {
    id: "flowworkshop-run-step",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-run-step",
    interaction_type: "execution",
    criticality: "high",
    expected_effect: "Replays the current flow step in isolation.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-run-step",
  },
  {
    id: "flowworkshop-resume-step",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-resume-step",
    interaction_type: "execution",
    criticality: "high",
    expected_effect: "Resumes the flow from the current step.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "toast-visible",
    case_id: "flowworkshop-resume-step",
  },
  {
    id: "flowworkshop-move-step-up",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-move-step-up",
    interaction_type: "list-action",
    criticality: "medium",
    expected_effect: "Moves the current step up.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-order-change",
    case_id: "flowworkshop-move-step-up",
  },
  {
    id: "flowworkshop-move-step-down",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-move-step-down",
    interaction_type: "list-action",
    criticality: "medium",
    expected_effect: "Moves the current step down.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-order-change",
    case_id: "flowworkshop-move-step-down",
  },
  {
    id: "flowworkshop-delete-step",
    component_source: "frontend",
    view: "FlowWorkshop",
    selector: "data-testid=flowworkshop-delete-step",
    interaction_type: "danger-action",
    criticality: "high",
    expected_effect: "Deletes the current step.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.flow-workshop.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "list-count-change",
    case_id: "flowworkshop-delete-step",
  },
  {
    id: "terminal-clear",
    component_source: "frontend",
    view: "Terminal",
    selector: "data-testid=terminal-clear",
    interaction_type: "utility",
    criticality: "medium",
    expected_effect: "Clears the terminal log display.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.terminal.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "terminal-clear",
  },
  {
    id: "terminal-height",
    component_source: "frontend",
    view: "Terminal",
    selector: "data-testid=terminal-height",
    interaction_type: "utility",
    criticality: "medium",
    expected_effect: "Adjusts the terminal height.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.terminal.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "terminal-height-change",
  },
  {
    id: "terminal-filter",
    component_source: "frontend",
    view: "Terminal",
    selector: "data-testid=terminal-filter",
    interaction_type: "utility",
    criticality: "medium",
    expected_effect: "Filters terminal logs by level.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.terminal.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "terminal-filter-errors",
  },
  {
    id: "terminal-autoscroll",
    component_source: "frontend",
    view: "Terminal",
    selector: "data-testid=terminal-autoscroll",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Toggles terminal auto-scroll.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.terminal.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "terminal-autoscroll-toggle",
  },
  {
    id: "onboarding-close-backdrop",
    component_source: "frontend",
    view: "Onboarding",
    selector: "data-testid=onboarding-close-backdrop",
    interaction_type: "dialog",
    criticality: "medium",
    expected_effect: "Closes the onboarding guide by clicking the overlay.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.onboarding.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "storage-change",
    case_id: "onboarding-close-backdrop",
  },
  {
    id: "onboarding-skip",
    component_source: "frontend",
    view: "Onboarding",
    selector: "data-testid=onboarding-skip",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Skips the onboarding guide.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.onboarding.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "storage-change",
    case_id: "onboarding-skip",
  },
  {
    id: "onboarding-prev",
    component_source: "frontend",
    view: "Onboarding",
    selector: "data-testid=onboarding-prev",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Returns to the previous onboarding step.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.onboarding.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "onboarding-prev",
  },
  {
    id: "onboarding-next",
    component_source: "frontend",
    view: "Onboarding",
    selector: "data-testid=onboarding-next",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Moves to the next onboarding step.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.onboarding.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "text-visible",
    case_id: "onboarding-next",
  },
  {
    id: "onboarding-start",
    component_source: "frontend",
    view: "Onboarding",
    selector: "data-testid=onboarding-start",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Completes onboarding and enters the main product flow.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.onboarding.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "storage-change",
    case_id: "onboarding-start",
  },
  {
    id: "params-toggle-api-key-visibility",
    component_source: "frontend",
    view: "Params",
    selector: "data-testid=params-toggle-api-key-visibility",
    interaction_type: "visibility-toggle",
    criticality: "medium",
    expected_effect: "Toggles the Gemini API key input between password and text.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.params.spec.ts",
    runtime_mode: "stub",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "params-toggle-api-key-visibility",
  },
  {
    id: "params-toggle-headless",
    component_source: "frontend",
    view: "Params",
    selector: "data-testid=params-toggle-headless",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Toggles headless mode.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.params.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "params-toggle-headless",
  },
  {
    id: "params-toggle-midscene-strict",
    component_source: "frontend",
    view: "Params",
    selector: "data-testid=params-toggle-midscene-strict",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Toggles Midscene Strict matching.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/frontend-e2e/button-behavior.params.spec.ts",
    runtime_mode: "both",
    is_apps_web: false,
    last_verified_command: "pnpm test:e2e:frontend:critical",
    assertion_type: "attribute-change",
    case_id: "params-toggle-midscene-strict",
  },
  {
    id: "appsweb-nav-home",
    component_source: "tests/web-harness",
    view: "AppsWebNav",
    selector: "data-testid=nav-home",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Navigates to the Home page.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "aria-current",
    case_id: "appsweb-nav-home",
  },
  {
    id: "appsweb-nav-about",
    component_source: "tests/web-harness",
    view: "AppsWebNav",
    selector: "data-testid=nav-about",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Navigates to the About page.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "aria-current",
    case_id: "appsweb-nav-about",
  },
  {
    id: "appsweb-nav-contact",
    component_source: "tests/web-harness",
    view: "AppsWebNav",
    selector: "data-testid=nav-contact",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Navigates to the Contact page.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "aria-current",
    case_id: "appsweb-nav-contact",
  },
  {
    id: "appsweb-nav-safe",
    component_source: "tests/web-harness",
    view: "AppsWebNav",
    selector: "data-testid=nav-safe",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Navigates to the Safe page.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "aria-current",
    case_id: "appsweb-nav-safe",
  },
  {
    id: "appsweb-nav-stories",
    component_source: "tests/web-harness",
    view: "AppsWebNav",
    selector: "data-testid=nav-stories",
    interaction_type: "navigation",
    criticality: "medium",
    expected_effect: "Navigates to the Story demo page.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "aria-current",
    case_id: "appsweb-nav-stories",
  },
  {
    id: "appsweb-counter-inc",
    component_source: "tests/web-harness",
    view: "AppsWebCounter",
    selector: "data-testid=counter-inc",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Increments the counter.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/ct/counter-card.spec.tsx",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command: "pnpm test:ct",
    assertion_type: "text-visible",
    case_id: "appsweb-counter-inc",
  },
  {
    id: "appsweb-counter-dec",
    component_source: "tests/web-harness",
    view: "AppsWebCounter",
    selector: "data-testid=counter-dec",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Decrements the counter.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/ct/counter-card.spec.tsx",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command: "pnpm test:ct",
    assertion_type: "text-visible",
    case_id: "appsweb-counter-dec",
  },
  {
    id: "appsweb-counter-reset",
    component_source: "tests/web-harness",
    view: "AppsWebCounter",
    selector: "data-testid=counter-reset",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Resets the counter to zero.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/ct/counter-card.spec.tsx",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command: "pnpm test:ct",
    assertion_type: "text-visible",
    case_id: "appsweb-counter-reset",
  },
  {
    id: "appsweb-feedback-submit",
    component_source: "tests/web-harness",
    view: "AppsWebFeedback",
    selector: "data-testid=feedback-submit",
    interaction_type: "form-submit",
    criticality: "medium",
    expected_effect: "Submits the feedback form and shows the resulting status.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "text-visible",
    case_id: "appsweb-feedback-submit",
  },
  {
    id: "appsweb-safe-toggle",
    component_source: "tests/web-harness",
    view: "AppsWebSafe",
    selector: "data-testid=safe-toggle",
    interaction_type: "state-toggle",
    criticality: "medium",
    expected_effect: "Toggles the safe-mode switch.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "attribute-change",
    case_id: "appsweb-safe-toggle",
  },
  {
    id: "appsweb-about-toggle",
    component_source: "tests/web-harness",
    view: "AppsWebAbout",
    selector: "data-testid=about-toggle",
    interaction_type: "visibility-toggle",
    criticality: "medium",
    expected_effect: "Expands or collapses the about details.",
    coverage_scope: "behavior-gated",
    spec_file: "tests/web-harness/tests/e2e/button-behavior.spec.ts",
    runtime_mode: "stub",
    is_apps_web: true,
    last_verified_command:
      "pnpm exec playwright test -c tests/web-harness/tests/e2e/playwright.config.ts tests/web-harness/tests/e2e/button-behavior.spec.ts",
    assertion_type: "visibility-toggle",
    case_id: "appsweb-about-toggle",
  },
] as const satisfies readonly ButtonBehaviorManifestEntry[];
