// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

export const DEFAULT_REQUEST_TIMEOUT_MS = 30_000;

let defaultRequestTimeoutMs = DEFAULT_REQUEST_TIMEOUT_MS;

export type RequestJsonInit = RequestInit & {
  timeoutMs?: number;
};

type StructuredErrorBody = {
  detail?: unknown;
  message?: unknown;
  error?: unknown;
  rawText?: string;
};

export class ApiRequestError extends Error {
  readonly status: number;
  readonly statusText: string;
  readonly method: string;
  readonly url: string;
  readonly body: StructuredErrorBody;

  constructor(
    message: string,
    details: {
      status: number;
      statusText: string;
      method: string;
      url: string;
      body: StructuredErrorBody;
    },
  ) {
    super(message);
    this.name = "ApiRequestError";
    this.status = details.status;
    this.statusText = details.statusText;
    this.method = details.method;
    this.url = details.url;
    this.body = details.body;
  }
}

export function setDefaultRequestTimeoutMs(timeoutMs: number): void {
  if (!Number.isFinite(timeoutMs) || timeoutMs < 0) {
    throw new Error("default request timeout must be a non-negative finite number");
  }
  defaultRequestTimeoutMs = timeoutMs;
}

function isJsonContentType(contentType: string): boolean {
  return contentType.includes("application/json") || contentType.includes("+json");
}

function tryParseJson(value: string): unknown | undefined {
  try {
    return JSON.parse(value);
  } catch {
    return undefined;
  }
}

function toDiagnosticText(value: unknown): string | undefined {
  if (typeof value === "string" && value.trim().length > 0) {
    return value;
  }
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }
  if (value && typeof value === "object") {
    const messageValue = (value as Record<string, unknown>).message;
    if (typeof messageValue === "string" && messageValue.trim().length > 0) {
      return messageValue;
    }
  }
  return undefined;
}

function buildErrorBody(text: string): StructuredErrorBody {
  const structured: StructuredErrorBody = {};
  if (text.length === 0) {
    return structured;
  }
  const parsed = tryParseJson(text);
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    const parsedObject = parsed as Record<string, unknown>;
    if ("detail" in parsedObject) structured.detail = parsedObject.detail;
    if ("message" in parsedObject) structured.message = parsedObject.message;
    if ("error" in parsedObject) structured.error = parsedObject.error;
  }
  structured.rawText = text;
  return structured;
}

function buildErrorMessage(status: number, statusText: string, body: StructuredErrorBody): string {
  const diagnostic = [
    toDiagnosticText(body.detail),
    toDiagnosticText(body.message),
    toDiagnosticText(body.error),
    body.rawText?.trim() || undefined,
  ].find((value) => value && value.length > 0);
  if (!diagnostic) {
    return `API request failed: ${status} ${statusText}`;
  }
  return `API request failed: ${status} ${statusText} - ${diagnostic}`;
}

function mergeAbortSignal(timeoutMs: number, externalSignal?: AbortSignal): {
  signal: AbortSignal | undefined;
  cleanup: () => void;
} {
  if (!externalSignal && timeoutMs <= 0) {
    return { signal: undefined, cleanup: () => {} };
  }
  if (externalSignal && timeoutMs <= 0) {
    return { signal: externalSignal, cleanup: () => {} };
  }

  const controller = new AbortController();
  const abortFromExternal = () => {
    controller.abort(externalSignal?.reason);
  };
  if (externalSignal?.aborted) {
    abortFromExternal();
  } else if (externalSignal) {
    externalSignal.addEventListener("abort", abortFromExternal, { once: true });
  }

  const timeoutHandle = setTimeout(() => {
    controller.abort(new Error(`Request timed out after ${timeoutMs}ms`));
  }, timeoutMs);

  return {
    signal: controller.signal,
    cleanup: () => {
      clearTimeout(timeoutHandle);
      if (externalSignal) {
        externalSignal.removeEventListener("abort", abortFromExternal);
      }
    },
  };
}

export async function requestJson(
  baseUrl: string,
  path: string,
  method: string,
  init?: RequestJsonInit,
): Promise<unknown> {
  const { timeoutMs, signal: externalSignal, ...fetchInit } = init ?? {};
  const timeoutWithDefault = timeoutMs ?? defaultRequestTimeoutMs;

  const headers = new Headers(fetchInit.headers ?? {});
  if (!headers.has("content-type") && init?.body) {
    headers.set("content-type", "application/json");
  }
  const { signal, cleanup } = mergeAbortSignal(timeoutWithDefault, externalSignal);

  try {
    const response = await fetch(`${baseUrl}${path}`, {
      ...fetchInit,
      method,
      headers,
      signal,
    });
    const text = await response.text();
    if (!response.ok) {
      const body = buildErrorBody(text);
      throw new ApiRequestError(buildErrorMessage(response.status, response.statusText, body), {
        status: response.status,
        statusText: response.statusText,
        method,
        url: `${baseUrl}${path}`,
        body,
      });
    }
    if (text.length === 0) {
      return undefined;
    }
    const contentType = response.headers.get("content-type")?.toLowerCase() ?? "";
    if (!isJsonContentType(contentType)) {
      return text;
    }
    try {
      return JSON.parse(text);
    } catch {
      throw new Error("API response is not valid JSON");
    }
  } finally {
    cleanup();
  }
}
