// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

import { requestJson } from "../core/request";

export async function getCsrfToken(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/csrf`,
    "GET",
    init,
  );
}

export async function postRegisterUser(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/register`,
    "POST",
    init,
  );
}

export async function listAutomationCommands(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/automation/commands`,
    "GET",
    init,
  );
}

export async function listAutomationTasks(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/automation/tasks`,
    "GET",
    init,
  );
}

export async function getAutomationTask(
  baseUrl: string,
  pathParams: { task_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/automation/tasks/${encodeURIComponent(pathParams.task_id)}`,
    "GET",
    init,
  );
}

export async function runAutomationCommand(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/automation/run`,
    "POST",
    init,
  );
}

export async function cancelAutomationTask(
  baseUrl: string,
  pathParams: { task_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/automation/tasks/${encodeURIComponent(pathParams.task_id)}/cancel`,
    "POST",
    init,
  );
}

export async function createComputerUseSession(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/computer-use/sessions`,
    "POST",
    init,
  );
}

export async function previewComputerUseAction(
  baseUrl: string,
  pathParams: { session_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/preview`,
    "POST",
    init,
  );
}

export async function confirmComputerUseAction(
  baseUrl: string,
  pathParams: { session_id: string; action_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/confirm/${encodeURIComponent(pathParams.action_id)}`,
    "POST",
    init,
  );
}

export async function executeComputerUseAction(
  baseUrl: string,
  pathParams: { session_id: string; action_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/execute/${encodeURIComponent(pathParams.action_id)}`,
    "POST",
    init,
  );
}

export async function readComputerUseEvidence(
  baseUrl: string,
  pathParams: { session_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/computer-use/sessions/${encodeURIComponent(pathParams.session_id)}/evidence`,
    "GET",
    init,
  );
}

export async function createBatchEmbeddings(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/embeddings/batch`,
    "POST",
    init,
  );
}

export async function listSessions(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/sessions`,
    "GET",
    init,
  );
}

export async function startSession(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/sessions/start`,
    "POST",
    init,
  );
}

export async function finishSession(
  baseUrl: string,
  pathParams: { session_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/sessions/${encodeURIComponent(pathParams.session_id)}/finish`,
    "POST",
    init,
  );
}

export async function listFlows(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/flows`,
    "GET",
    init,
  );
}

export async function createFlow(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/flows`,
    "POST",
    init,
  );
}

export async function importLatestFlow(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/flows/import-latest`,
    "POST",
    init,
  );
}

export async function getFlow(
  baseUrl: string,
  pathParams: { flow_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/flows/${encodeURIComponent(pathParams.flow_id)}`,
    "GET",
    init,
  );
}

export async function patchFlow(
  baseUrl: string,
  pathParams: { flow_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/flows/${encodeURIComponent(pathParams.flow_id)}`,
    "PATCH",
    init,
  );
}

export async function listTemplates(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates`,
    "GET",
    init,
  );
}

export async function createTemplate(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates`,
    "POST",
    init,
  );
}

export async function postTemplatesFromArtifacts(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/from-artifacts`,
    "POST",
    init,
  );
}

export async function getTemplate(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/${encodeURIComponent(pathParams.template_id)}`,
    "GET",
    init,
  );
}

export async function patchTemplate(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/${encodeURIComponent(pathParams.template_id)}`,
    "PATCH",
    init,
  );
}

export async function exportTemplate(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/${encodeURIComponent(pathParams.template_id)}/export`,
    "GET",
    init,
  );
}

export async function promoteTemplate(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/promote`,
    "POST",
    init,
  );
}

export async function getTemplateHistory(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/${encodeURIComponent(pathParams.template_id)}/history`,
    "GET",
    init,
  );
}

export async function forkTemplateVersion(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/${encodeURIComponent(pathParams.template_id)}/fork-version`,
    "POST",
    init,
  );
}

export async function markTemplateRecommended(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/templates/${encodeURIComponent(pathParams.template_id)}/mark-recommended`,
    "POST",
    init,
  );
}

export async function resolveProfile(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/profiles/resolve`,
    "POST",
    init,
  );
}

export async function previewReconstruction(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/reconstruction/preview`,
    "POST",
    init,
  );
}

export async function generateReconstruction(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/reconstruction/generate`,
    "POST",
    init,
  );
}

export async function listRuns(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/runs`,
    "GET",
    init,
  );
}

export async function createRun(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/runs`,
    "POST",
    init,
  );
}

export async function getRun(
  baseUrl: string,
  pathParams: { run_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/runs/${encodeURIComponent(pathParams.run_id)}`,
    "GET",
    init,
  );
}

export async function submitRunOtp(
  baseUrl: string,
  pathParams: { run_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/runs/${encodeURIComponent(pathParams.run_id)}/otp`,
    "POST",
    init,
  );
}

export async function resumeRun(
  baseUrl: string,
  pathParams: { run_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/runs/${encodeURIComponent(pathParams.run_id)}/resume`,
    "POST",
    init,
  );
}

export async function cancelRun(
  baseUrl: string,
  pathParams: { run_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/runs/${encodeURIComponent(pathParams.run_id)}/cancel`,
    "POST",
    init,
  );
}

export async function listProofCampaigns(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/campaigns`,
    "GET",
    init,
  );
}

export async function createProofCampaign(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/campaigns`,
    "POST",
    init,
  );
}

export async function getProofCampaign(
  baseUrl: string,
  pathParams: { campaign_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/campaigns/${encodeURIComponent(pathParams.campaign_id)}`,
    "GET",
    init,
  );
}

export async function diffProofCampaign(
  baseUrl: string,
  pathParams: { campaign_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/campaigns/${encodeURIComponent(pathParams.campaign_id)}/diff`,
    "POST",
    init,
  );
}

export async function compareRunsForProof(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/runs/compare`,
    "POST",
    init,
  );
}

export async function getRunAiReviewProjection(
  baseUrl: string,
  pathParams: { run_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/runs/${encodeURIComponent(pathParams.run_id)}/ai-review`,
    "GET",
    init,
  );
}

export async function getTemplateTargetFeasibility(
  baseUrl: string,
  pathParams: { template_id: string },
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/proof/templates/${encodeURIComponent(pathParams.template_id)}/feasibility`,
    "GET",
    init,
  );
}

export async function getVonageInboundSms(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/integrations/vonage/inbound-sms`,
    "GET",
    init,
  );
}

export async function postVonageInboundSms(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/integrations/vonage/inbound-sms`,
    "POST",
    init,
  );
}

export const AUTOMATION_API_OPERATIONS = [
  {
    operationId: "getCsrfToken",
    method: "GET",
    path: "/api/csrf",
  },
  {
    operationId: "postRegisterUser",
    method: "POST",
    path: "/api/register",
  },
  {
    operationId: "listAutomationCommands",
    method: "GET",
    path: "/api/automation/commands",
  },
  {
    operationId: "listAutomationTasks",
    method: "GET",
    path: "/api/automation/tasks",
  },
  {
    operationId: "getAutomationTask",
    method: "GET",
    path: "/api/automation/tasks/{task_id}",
  },
  {
    operationId: "runAutomationCommand",
    method: "POST",
    path: "/api/automation/run",
  },
  {
    operationId: "cancelAutomationTask",
    method: "POST",
    path: "/api/automation/tasks/{task_id}/cancel",
  },
  {
    operationId: "createComputerUseSession",
    method: "POST",
    path: "/api/computer-use/sessions",
  },
  {
    operationId: "previewComputerUseAction",
    method: "POST",
    path: "/api/computer-use/sessions/{session_id}/preview",
  },
  {
    operationId: "confirmComputerUseAction",
    method: "POST",
    path: "/api/computer-use/sessions/{session_id}/confirm/{action_id}",
  },
  {
    operationId: "executeComputerUseAction",
    method: "POST",
    path: "/api/computer-use/sessions/{session_id}/execute/{action_id}",
  },
  {
    operationId: "readComputerUseEvidence",
    method: "GET",
    path: "/api/computer-use/sessions/{session_id}/evidence",
  },
  {
    operationId: "createBatchEmbeddings",
    method: "POST",
    path: "/api/embeddings/batch",
  },
  {
    operationId: "listSessions",
    method: "GET",
    path: "/api/sessions",
  },
  {
    operationId: "startSession",
    method: "POST",
    path: "/api/sessions/start",
  },
  {
    operationId: "finishSession",
    method: "POST",
    path: "/api/sessions/{session_id}/finish",
  },
  {
    operationId: "listFlows",
    method: "GET",
    path: "/api/flows",
  },
  {
    operationId: "createFlow",
    method: "POST",
    path: "/api/flows",
  },
  {
    operationId: "importLatestFlow",
    method: "POST",
    path: "/api/flows/import-latest",
  },
  {
    operationId: "getFlow",
    method: "GET",
    path: "/api/flows/{flow_id}",
  },
  {
    operationId: "patchFlow",
    method: "PATCH",
    path: "/api/flows/{flow_id}",
  },
  {
    operationId: "listTemplates",
    method: "GET",
    path: "/api/templates",
  },
  {
    operationId: "createTemplate",
    method: "POST",
    path: "/api/templates",
  },
  {
    operationId: "postTemplatesFromArtifacts",
    method: "POST",
    path: "/api/templates/from-artifacts",
  },
  {
    operationId: "getTemplate",
    method: "GET",
    path: "/api/templates/{template_id}",
  },
  {
    operationId: "patchTemplate",
    method: "PATCH",
    path: "/api/templates/{template_id}",
  },
  {
    operationId: "exportTemplate",
    method: "GET",
    path: "/api/templates/{template_id}/export",
  },
  {
    operationId: "promoteTemplate",
    method: "POST",
    path: "/api/templates/promote",
  },
  {
    operationId: "getTemplateHistory",
    method: "GET",
    path: "/api/templates/{template_id}/history",
  },
  {
    operationId: "forkTemplateVersion",
    method: "POST",
    path: "/api/templates/{template_id}/fork-version",
  },
  {
    operationId: "markTemplateRecommended",
    method: "POST",
    path: "/api/templates/{template_id}/mark-recommended",
  },
  {
    operationId: "resolveProfile",
    method: "POST",
    path: "/api/profiles/resolve",
  },
  {
    operationId: "previewReconstruction",
    method: "POST",
    path: "/api/reconstruction/preview",
  },
  {
    operationId: "generateReconstruction",
    method: "POST",
    path: "/api/reconstruction/generate",
  },
  {
    operationId: "listRuns",
    method: "GET",
    path: "/api/runs",
  },
  {
    operationId: "createRun",
    method: "POST",
    path: "/api/runs",
  },
  {
    operationId: "getRun",
    method: "GET",
    path: "/api/runs/{run_id}",
  },
  {
    operationId: "submitRunOtp",
    method: "POST",
    path: "/api/runs/{run_id}/otp",
  },
  {
    operationId: "resumeRun",
    method: "POST",
    path: "/api/runs/{run_id}/resume",
  },
  {
    operationId: "cancelRun",
    method: "POST",
    path: "/api/runs/{run_id}/cancel",
  },
  {
    operationId: "listProofCampaigns",
    method: "GET",
    path: "/api/proof/campaigns",
  },
  {
    operationId: "createProofCampaign",
    method: "POST",
    path: "/api/proof/campaigns",
  },
  {
    operationId: "getProofCampaign",
    method: "GET",
    path: "/api/proof/campaigns/{campaign_id}",
  },
  {
    operationId: "diffProofCampaign",
    method: "POST",
    path: "/api/proof/campaigns/{campaign_id}/diff",
  },
  {
    operationId: "compareRunsForProof",
    method: "POST",
    path: "/api/proof/runs/compare",
  },
  {
    operationId: "getRunAiReviewProjection",
    method: "GET",
    path: "/api/proof/runs/{run_id}/ai-review",
  },
  {
    operationId: "getTemplateTargetFeasibility",
    method: "GET",
    path: "/api/proof/templates/{template_id}/feasibility",
  },
  {
    operationId: "getVonageInboundSms",
    method: "GET",
    path: "/api/integrations/vonage/inbound-sms",
  },
  {
    operationId: "postVonageInboundSms",
    method: "POST",
    path: "/api/integrations/vonage/inbound-sms",
  },
] as const;
