// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.

import { requestJson } from "../core/request";

export async function getCommandTowerOverview(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/overview`,
    "GET",
    init,
  );
}

export async function getCommandTowerLatestFlow(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/latest-flow`,
    "GET",
    init,
  );
}

export async function getCommandTowerLatestFlowDraft(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/latest-flow-draft`,
    "GET",
    init,
  );
}

export async function patchCommandTowerLatestFlowDraft(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/latest-flow-draft`,
    "PATCH",
    init,
  );
}

export async function postCommandTowerReplayLatest(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/replay-latest`,
    "POST",
    init,
  );
}

export async function postCommandTowerOrchestrateFromArtifacts(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/orchestrate-from-artifacts`,
    "POST",
    init,
  );
}

export async function postCommandTowerReplayLatestFromStep(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/replay-latest-from-step`,
    "POST",
    init,
  );
}

export async function postCommandTowerReplayLatestStep(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/replay-latest-step`,
    "POST",
    init,
  );
}

export async function getCommandTowerStepEvidence(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/evidence`,
    "GET",
    init,
  );
}

export async function getCommandTowerEvidenceTimeline(
  baseUrl: string,
  init?: RequestInit,
): Promise<unknown> {
  return requestJson(
    baseUrl,
    `/api/command-tower/evidence-timeline`,
    "GET",
    init,
  );
}

export const COMMAND_TOWER_API_OPERATIONS = [
  {
    operationId: "getCommandTowerOverview",
    method: "GET",
    path: "/api/command-tower/overview",
  },
  {
    operationId: "getCommandTowerLatestFlow",
    method: "GET",
    path: "/api/command-tower/latest-flow",
  },
  {
    operationId: "getCommandTowerLatestFlowDraft",
    method: "GET",
    path: "/api/command-tower/latest-flow-draft",
  },
  {
    operationId: "patchCommandTowerLatestFlowDraft",
    method: "PATCH",
    path: "/api/command-tower/latest-flow-draft",
  },
  {
    operationId: "postCommandTowerReplayLatest",
    method: "POST",
    path: "/api/command-tower/replay-latest",
  },
  {
    operationId: "postCommandTowerOrchestrateFromArtifacts",
    method: "POST",
    path: "/api/command-tower/orchestrate-from-artifacts",
  },
  {
    operationId: "postCommandTowerReplayLatestFromStep",
    method: "POST",
    path: "/api/command-tower/replay-latest-from-step",
  },
  {
    operationId: "postCommandTowerReplayLatestStep",
    method: "POST",
    path: "/api/command-tower/replay-latest-step",
  },
  {
    operationId: "getCommandTowerStepEvidence",
    method: "GET",
    path: "/api/command-tower/evidence",
  },
  {
    operationId: "getCommandTowerEvidenceTimeline",
    method: "GET",
    path: "/api/command-tower/evidence-timeline",
  },
] as const;
