// Auto-generated by contracts/scripts/generate-client.ts. Do not edit manually.
import { AUTOMATION_API_OPERATIONS } from "./api/automation";
import { COMMAND_TOWER_API_OPERATIONS } from "./api/command-tower";
import { HEALTH_API_OPERATIONS } from "./api/health";

export * from "./api/automation";
export * from "./api/command-tower";
export * from "./api/health";

export const API_OPERATIONS = [
  ...HEALTH_API_OPERATIONS,
  ...AUTOMATION_API_OPERATIONS,
  ...COMMAND_TOWER_API_OPERATIONS,
] as const;
